// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIBjTPCgpiD9nuKs8PgYq8bafkUATE5uo',
    appId: '1:460647169637:web:a464f619167e250695108c',
    messagingSenderId: '460647169637',
    projectId: 'jokenpoapp',
    authDomain: 'jokenpoapp.firebaseapp.com',
    storageBucket: 'jokenpoapp.appspot.com',
    measurementId: 'G-7QQH5W1NL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_1iEm2g4_tqw-Keefv8TfuR7tjrg2N0k',
    appId: '1:460647169637:android:9706285562392b7a95108c',
    messagingSenderId: '460647169637',
    projectId: 'jokenpoapp',
    storageBucket: 'jokenpoapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM0h2Zj8A_AgpHGcw2H_srb1_dyXD1ZtM',
    appId: '1:460647169637:ios:40e1f1f8cd1af41195108c',
    messagingSenderId: '460647169637',
    projectId: 'jokenpoapp',
    storageBucket: 'jokenpoapp.appspot.com',
    iosClientId: '460647169637-5jstq7jbevfbrkntd6c8svuq5ls8698v.apps.googleusercontent.com',
    iosBundleId: 'com.example.projeto',
  );
}
